### ISSUE TITLE
Emacs 中 Python 交互模式下缩进报错：unexpected indent

### ISSUE THREAD

**Issue by samualle** [zhengfaxiang/emacs.d#2]
macOS 10.12.3系统，Python 版本是3.6.0，Emacs 版本25.1，在 Emacs 中进入 python-mode，在Python 的交互环境下进行缩进，无论是用 tab 键或者space 键，都会报错，错误信息是：unexpected indent。同样的代码，在终端里的 Python 交互模式下就不会报错了。不知道能否指点一二，谢谢。

**Comment by fzh3g** [comment]
多行命令可以试下用`C-j`代替回车

**Comment by fzh3g** [comment]
如果解决了你的问题，我把issue关了哈～

**Comment by samualle** [comment]
已经解决了，谢谢。
